syntax = "proto3";

package protocol;
option csharp_namespace = "Couchbase.Grpc.Protocol";
option java_package = "com.couchbase.client.performer.grpc";
option go_package = "github.com/couchbaselabs/transactions-fit-performer/protocol";
option java_multiple_files = true;

message Content {
  oneof content {
    // This should be passed directly into the SDK, as string type - no initial conversion into a JsonObject or similar.
    // How this is treated by the SDK will depend on the transcoder set (if any), which is sent separately in the options.
    string passthroughString = 1;

    // In future we may want to passthrough raw byte strings, or the SDK to encode it first into various forms
  }
}