syntax = "proto3";

package protocol.sdk.kv.rangescan;
option csharp_namespace = "Couchbase.Grpc.Protocol.Sdk.Kv.RangeScan";
option java_package = "com.couchbase.client.protocol.sdk.kv.rangescan";
option go_package = "github.com/couchbaselabs/transactions-fit-performer/protocol/sdk/kv/rangescan";
option java_multiple_files = true;

import "shared.basic.proto";
import "shared.collection.proto";
import "shared.content.proto";
import "shared.transcoders.proto";
import "streams.top_level.proto";

message ScanTerm {
  string term = 1;
  optional bool exclusive = 2;
}

message ScanTermChoice {
  oneof choice {
    bool minimum = 1;
    bool maximum = 2;
    ScanTerm term = 3;
  }
}

message RangeScan {
  ScanTermChoice from = 1;
  ScanTermChoice to = 2;
}

message SamplingScan {
  uint64 limit = 1;
  optional uint64 seed = 2;
}

message ScanType {
  oneof type {
    RangeScan range = 1;
    SamplingScan sampling = 2;
  }
}

enum ScanSort {
  KV_RANGE_SCAN_SORT_NONE = 0;
  KV_RANGE_SCAN_SORT_ASCENDING = 1;
}

message ScanOptions {
  // Note this field may have been subsequently renamed ids_only in the API.  Since it otherwise behaves identically and
  // there are existing performers that would be affected by a change here, it's left unchanged.
  optional bool without_content = 1;
  optional shared.MutationState consistent_with = 2;
  optional ScanSort sort = 3;
  optional shared.Transcoder transcoder = 4;
  optional int32 timeout_msecs = 5;
  // As usual, parent_span_id will only be sent if the performer declares support for Caps.OBSERVABILITY_1
  optional string parent_span_id = 6;
  optional int32 batch_byte_limit = 7;
  optional int32 batch_item_limit = 8;
}

message ScanResult {
  string id = 1;

  // Following three fields shouldn't be present if withoutContent was set.
  optional bytes content = 2;
  // Represented as the number of seconds since January 1, 1970 (e.g. what the server returns)
  optional int64 expiry_time = 3;
  optional int64 cas = 4;

  // Not part of the SDK response - identifies what stream this is from.
  string stream_id = 5;
}

// A Scan will result in the performer sending back a stream of (in the golden path):
// (1) A stream.Created result with type STREAM_KV_RANGE_SCAN, followed by
// (2) Zero or more ScanResult results (and/or streams.Error), followed by
// (1) A stream.Complete result.
//
// A streams.CancelRequest from the driver should be handled per the RFC - with a range scan cancellation sent to KV
// on each vbucket stream.
message Scan {
  shared.Collection collection = 1;
  ScanType scan_type = 2;
  optional ScanOptions options = 3;

  // Not sent on to the SDK - instead specifies how the performer should handle the streaming.
  streams.Config stream_config = 4;

  // Controls how all ScanResult.contentAs() calls are done by the SDK for this scan.
  // If not specified, the performer should not do contentAs.
  // If there is any error from result.contentAs(), each error needs to raise a streams.Error, instead of the normal ScanResult.
  optional shared.ContentAs content_as = 5;
}
