syntax = "proto3";

package protocol.sdk.management.collection.query;
option csharp_namespace = "Couchbase.Grpc.Protocol.Sdk.Management.Collection.Query";
option java_package = "com.couchbase.client.protocol.sdk.management.collection.query";
option go_package = "github.com/couchbaselabs/transactions-fit-performer/protocol/sdk/management/collection/query";
option java_multiple_files = true;

import "shared.collection.proto";
import "sdk.management.query.options.proto";


// This file is for CollectionQueryIndexManager: collection.queryIndexes()
// For Cluster-level query index manager (cluster.queryIndexes()), see sdk.management.query.proto.
//
// They have very similar, but not identical, APIs, and the APIs may diverge further in future.  So they are separated.
// Using the existing QueryIndexOptions is intentional, as that is what we are doing in the SDK also.

message GetAllIndexes {
  shared.Collection collection = 1;
  optional management.query.GetAllQueryIndexOptions options = 2;
}

message CreatePrimaryIndex {
  shared.Collection collection = 1;
  optional management.query.CreatePrimaryQueryIndexOptions options = 2;
}

message CreateIndex {
  shared.Collection collection = 1;
  string index_name = 2;
  repeated string fields = 3;
  optional management.query.CreateQueryIndexOptions options = 4;
}

message DropPrimaryIndex {
  shared.Collection collection = 1;
  optional management.query.DropPrimaryIndexOptions options = 2;
}

message DropIndex {
  shared.Collection collection = 1;
  string index_name = 2;
  optional management.query.DropIndexOptions options = 3;
}

message WatchIndexes {
  shared.Collection collection = 1;
  repeated string index_names = 2;
  int32 timeout_msecs = 3;
  optional management.query.WatchIndexesOptions options = 4;
}

message BuildDeferredIndexes {
  shared.Collection collection = 1;
  optional management.query.BuildDeferredIndexesOptions options = 2;
}

message Command {
  oneof command {
    CreatePrimaryIndex create_primary_index = 1;
    CreateIndex create_index = 2;
    GetAllIndexes get_all_indexes = 3;
    DropPrimaryIndex drop_primary_index = 4;
    DropIndex drop_index = 5;
    WatchIndexes watch_indexes = 6;
    BuildDeferredIndexes build_deferred_indexes = 7;
  }
}

