syntax = "proto3";

package protocol.sdk;
option csharp_namespace = "Couchbase.Grpc.Protocol.Sdk";
option java_package = "com.couchbase.client.protocol.sdk";
option go_package = "github.com/couchbaselabs/transactions-fit-performer/protocol/sdk";
option java_multiple_files = true;

import "shared.bounds.proto";
import "shared.exceptions.proto";
import "sdk.kv.rangescan.top_level.proto";
import "sdk.kv.commands.proto";
import "shared.basic.proto";
import "sdk.management.query.proto";

message Command {
  oneof command {
    kv.Insert insert = 1;
    kv.Get get = 2;
    kv.Remove remove = 3;
    kv.Replace replace = 4;
    kv.Upsert upsert = 5;
    kv.rangescan.Scan range_scan = 7;
    management.query.CreatePrimaryIndex create_primary_index = 9;
    management.query.CreateIndex create_index = 10;
    management.query.GetAllIndexes get_all_indexes = 11;
    management.query.DropPrimaryIndex drop_primary_index = 12;
    management.query.DropIndex drop_index = 13;
    management.query.WatchIndexes watch_indexes = 14;
    management.query.BuildDeferredIndexes build_deferred_indexes = 15;
  }

  // Whether the returned CommandResult should contain a full result or just `success`.  Used for performance tests
  // when the result doesn't matter so the small cost of creating it can be eliminated.
  bool return_result = 6;

  // The API to use to execute this command.
  shared.API api = 8;
}

// The result of executing a single sdk.Command.
message Result {
  oneof result {
    // If the small overhead of creating a full *Result is not required (e.g. for performance testing), can
    // return this generic success instead.  Controlled by SdkCommand.returnResult.
    bool success = 1;

    // If the operation failed.
    shared.Exception exception = 2;

    // If the operation succeeded and sdk.Command.returnResult==true, return one of these.
    kv.GetResult get_result = 3;
    kv.MutationResult mutation_result = 4;
    kv.rangescan.ScanResult range_scan_result = 5;

    // List of indexes returned by a GetAllIndexes request
    management.query.QueryIndexes query_indexes = 6;
  }
}

message Workload {
  // The commands to run.  The performer should execute these in a loop until `bounds` is completed.
  //
  // If there are multiple commands, each should register as separate command for the purposes of bounding, and each
  // should send back one CommandResult.
  //
  // For example, if the bounds specifies
  // to run 10 commands total, and there are 3 Command specified here, the performer should execute the 3 commands
  // 3 times, and then the first command once more.  And 10 sdk.Results will be sent back.
  //
  // If the command fails, the performer should not propagate the failure (but should still send back an sdk.Result).
  repeated Command command = 1;

  // Controls how the commands should be run.
  // If it's not present, just run the commands through once.
  optional shared.Bounds bounds = 2;
}

