syntax = "proto3";

package protocol.shared;
option csharp_namespace = "Couchbase.Grpc.Protocol.Shared";
option java_package = "com.couchbase.client.protocol.shared";
option go_package = "github.com/couchbaselabs/transactions-fit-performer/protocol/shared";
option java_multiple_files = true;

import "shared.transaction_config.proto";
import "shared.transcoders.proto";

message ClusterConfig {
    // Will only be sent to ExtSDKIntegration-enabled performers.
    optional TransactionsConfig transactionsConfig = 1;

    // The performer should use a custom JsonSerializer when creating the Cluster.
    // This custom JsonSerializer is required to have specific serialization and deserialization logic, which the driver
    // will validate.  See the Java performer for implementation details.
    bool useCustomSerializer = 2;

    // Used for TLS enabled clusters such as Capella clusters
    bool useTls = 3;
    optional string certPath = 4;

    // Following taken from:
    // https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0059-sdk3-foundation.md#configuration
    optional int32 kvConnectTimeoutSecs = 5;
    optional int32 kvTimeoutMillis = 6;
    optional int32 kvDurableTimeoutMillis = 7;
    optional int32 viewTimeoutSecs = 8;
    optional int32 queryTimeoutSecs = 9;
    optional int32 analyticsTimeoutSecs = 10;
    optional int32 searchTimeoutSecs = 11;
    optional int32 managementTimeoutSecs = 12;
    optional Transcoder transcoder = 13;
    optional bool enableMutationTokens = 14;
    optional int32 tcpKeepAliveTimeMillis = 15;
    optional bool enableTcpKeepAlives = 16;
    optional bool forceIPV4 = 17;
    optional int32 configPollIntervalSecs = 18;
    optional int32 configPollFloorIntervalSecs = 19;
    optional int32 configIdleRedialTimeoutSecs = 20;
    optional int32 numKvConnections = 21;
    optional int32 maxHttpConnections = 22;
    optional int32 idleHttpConnectionTimeoutSecs = 23;
}

// Only sent to ExtSDKIntegration-supporting performers.
// Creates a cluster connection, with an optional cluster & transactions configuration.
message ClusterConnectionCreateRequest {
    // The id to use for this connection.
    string clusterConnectionId = 1;

    // Details of the cluster connection.
    string clusterHostname = 2;
    string clusterUsername = 3;
    string clusterPassword = 4;

    optional ClusterConfig clusterConfig = 5;
}

message ClusterConnectionCreateResponse {
    // The number of cluster connections the performer has, after opening this one.
    int32 clusterConnectionCount = 1;
}

message ClusterConnectionCloseRequest {
    string clusterConnectionId = 1;
}

message ClusterConnectionCloseResponse {
    // The number of cluster connections the performer has, after closing this one.
    int32 clusterConnectionCount = 2;
}

message DisconnectConnectionsRequest {
}

message DisconnectConnectionsResponse {
}

