// Everything to do with testing of _txn:client-record
syntax = "proto3";

// See README.md in this directory for a description of these.
package protocol;
option csharp_namespace = "Couchbase.Grpc.Protocol";
option java_package = "com.couchbase.grpc.protocol";
option go_package = "github.com/couchbaselabs/transactions-fit-performer/protocol";
option java_multiple_files = true;

import "txn_hooks.proto";

message ClientRecordProcessRequest {
    string clientUUID = 1;
    string bucketName = 2;
    string scopeName = 3;
    string collectionName = 4;
    // Any hooks can only use HookPoints in the CLIENT_RECORD_* range
    repeated Hook hook = 5;
    string clusterConnectionId=6;
}

message ClientRecordProcessResponse {
    int32 numActiveClients = 1;
    int32 indexOfThisClient = 2;
    repeated string expiredClientIds = 4;
    int32 numExistingClients = 5;
    int32 numExpiredClients = 6;
    bool overrideEnabled = 7;
    bool overrideActive = 8;
    int64 overrideExpires = 9;
    int64 casNowNanos = 10;
    string clientUUID = 11;
    bool success = 12;
}

message ClientRecordRemoveRequest {
    string clientUUID = 1;
    // Any hooks can only use HookPoints in the CLIENT_RECORD_* range
    repeated Hook hook = 2;

    string clusterConnectionId=8;
}

message ClientRecordRemoveResponse {
    bool success = 1;
}
