syntax = "proto3";

package protocol;
option csharp_namespace = "Couchbase.Grpc.Protocol";
option java_package = "com.couchbase.client.performer.grpc";
option java_multiple_files = true;
option go_package = "github.com/couchbaselabs/perf-sdk/protocol";

import "sdk_commands.proto";
import "grpc_commands.proto";
import "google/protobuf/timestamp.proto";
import "txn_performer.proto";

// A workload is generally a bunch of commands to run.
message Workload {
  oneof workload {
    SdkWorkload sdk = 1;
    GrpcWorkload grpc = 2;
    // TransactionWorkload will follow
  }
}

// "HorizontalScaling" is an abstraction over there being many forms of concurrency.  The core idea is that the driver
// is trying to increase the parallelism, and it's up to the performer to choose a suitable platform-dependent way to
// do this.
// For some languages that will be threads.  For some, a larger pool of concurrent Future/Promises.  For some,
// forking a new process.
// Whatever is produced (thread, new process), it should run the provided workload in a tight loop.  So essentially
// HorizontalScaling is the number of concurrent operations taking place.
message HorizontalScaling {
  // Performer will run these workloads in this 'thread-like', in the specified order.
  repeated Workload workloads = 1;
}

message WorkloadRunRequest {
  // The previously established cluster connection to use
  string clusterConnectionId = 1;

  // See HorizontalScaling for a discussion of this.  Broadly, it's the number of concurrent operations
  // required.
  repeated HorizontalScaling horizontalScaling = 2;

  // Controls some meta aspects of how the performer should execute the run.
  optional RunConfig config = 3;
}

// Controls how the performer streams back results.
//
// The driver currently maintains a 10 second buffer, e.g. it is only writing data that's at least 10 seconds old.  This
// is to handle out-of-order responses from the performer and to give it some flexibility w.r.t. batching.  The performer
// should never send back data that is older than this buffer - the results are undefined if it does.
//
// Note that there is no provision for dropping packets currently.  It is expected that the performer (and driver, and
// network) can keep up streaming back results from any workload.  Workloads could potentially last multiple hours, even
// days, and most workloads will generate continuous traffic.

// See CBD-4975 for discussion of streaming.  The two main points are:
// 1. Naively sending back results one at a time did not scale.
// 2. Batching results in BatchedResults increased flow-rate by nearly 2 orders of magnitude.
message RunConfigStreaming {
  // The next two parameters are only mandatory on GrpcWorkloads, which are explicitly testing various streaming
  // approaches.  Otherwise they should be regarded as optional
  // hints.  If the performer follows them then it will automatically get what has been tested to most reliably
  // return results.  But it can override them if it has done its own testing and found its own best path for that
  // language.

  // If present, the performer should stream back BatchedResults, aiming to contain this number of results.
  // The performer can return less elements than this in a batch (so it does not have to wait for a write queue to
  // fill first).
  optional int32 batchSize = 1;

  // Whether the performer should enable flow control.  This will mean different things to different
  // GRPC implementations, but the concept is to only send responses when the GRPC response stream reports itself ready.
  // If the performer is unable to keep up with the flow rate then this effectively just moves the filling queue from
  // GRPC's to one owned by the performer, but this can still be beneficial as the performer can keep better metrics
  // on its own queue.
  bool flowControl = 2;

  // Whether the performer should stream back metrics.
  bool enableMetrics = 3;
}

message RunConfig {
  optional RunConfigStreaming streamingConfig = 1;
}

// For optimal streaming performance, batches of WorkloadSingleResult can be returned.
message BatchedResult {
  repeated WorkloadSingleResult result = 1;
}

// Running a workload results in a stream or list of these.
message WorkloadSingleResult {
  oneof result {
    // Each SdkCommand should return back one of these results.  There is no requirement for these to be in sorted order - the driver
    // will take care of that.
    WorkloadRunCommandResult commandResult = 1;

    // The performer can send back metrics whenever it wishes.  However, due to the way database results are currently
    // joined with the bucket results (which are in one second buckets), it's only useful to send back a maximum of
    // one per second.
    MetricsResult metricsResult = 2;

    // Each GrpcCommand should return back one of these results.  There is no requirement for these to be in sorted order - the driver
    // will take care of that.
    GrpcResult grpcResult = 3;

    // For optimal streaming performance, batches of results can be returned.
    BatchedResult batchedResult = 4;
  }
}


message MetricsResult {
  // A JSON blob that can contain any information the performer likes.  '{"cpu":83}' for example.  It will be written
  // directly into the database.
  // The performer can return whatever fields it wants, named whatever it wants (with some consideration given to database
  // size).  But if it is returning any of the following it should use these standardised field names:
  // memHeapUsedMB:  how much heap memory has been used by the performer+SDK, in MB
  // processCpu:     how much CPU (total, across all cores) the performer+SDK is using
  // systemCpu:      how much CPU (total, across all cores) the whole system is using
  // threadCount:    how many threads the performer+SDK are using
  string metrics = 1;
  google.protobuf.Timestamp initiated = 2;
}

message GrpcPingResult {
}

message GrpcResult {
  oneof result {
    GrpcPingResult pingResult = 1;
  }
}


// Each command in a workload should send back one of these
message WorkloadRunCommandResult {
  oneof result {
    // Each SdkCommand should return back one of these results.
    SdkCommandResult sdkResult = 1;

    // Not used now, but will be later
    TransactionResult transactionResult = 4;
  }

  // Performance times are always returned so it's easier for the performers to code-share between performance and
  // integration testing.
  //
  // Clocks are hard.  Many OS/platform combinations cannot guarantee nanosecond level precision of a wallclock time,
  // but can provide such precision for elapsed time.
  // So:
  //
  // `elapsedNanos` is intended to be, as precisely as the platform can measure it, the exact time taken by the operation in nanoseconds.
  // Measured from just before sending the operation into the SDK (e.g. after handling any GRPC work and JSON conversion), and just after
  // the SDK returns.  To stress, this should not include any JSON processing.
  //
  // `initiated` is a wallclock time, used to place this operation into a one second bucket.  This should be as
  // accurate as the platform can provide (often realistically this is only accurate to 10 millis or so).  Hopefully
  // a few operations ending up in the wrong bucket each second will not dramatically impact the results.  It is ok
  // to set `initiated` before the GRPC work, due to the reduced precision.
  // If the operation fails, the performer does not need to set `elapsedNanos` - it will not be used.  However `initiated`
  // must always be sent.
  int64 elapsedNanos = 2;
  google.protobuf.Timestamp initiated = 3;
}

// A WorkloadRunRequest results in a list of WorkloadRunSingleResult.  Will generally be one per *Command (SdkCommand, etc.)
message WorkloadRunResult {
  repeated WorkloadSingleResult results = 1;
}
